/*Mocked datas for the employee array*/
const employees = [
  {
    id: "748",
    firstname: "Freddy",
    lastname: "Krueguer",
    startdate: "10/31/78",
    department: "Human Ressources",
    birthday: "02/23/60",
    street: "Elm Street",
    city: "Springwood",
    state: "OH",
    zipcode: "45011",
  },
  {
    id: "1384",
    firstname: "Jason",
    lastname: "Voorhees",
    startdate: "10/31/81",
    department: "Marketing",
    birthday: "11/02/61",
    street: "Franklin Street",
    city: "Crystal Lake",
    state: "NJ",
    zipcode: "75624",
  },
  {
    id: "258",
    firstname: "Ash",
    lastname: "Williams",
    startdate: "04/11/89",
    department: "Sales",
    birthday: "06/02/69",
    street: "Clatu Verata Street",
    city: "Elk Grove",
    state: "MI",
    zipcode: "96425",
  },
  {
    id: "75",
    firstname: "Annie",
    lastname: "Wilkes",
    startdate: "10/01/89",
    department: "Legal",
    birthday: "09/05/70",
    street: "Sheldon Street",
    city: "Sidewinter",
    state: "CO",
    zipcode: "24586",
  },
];

export default employees;
