/*Mocked datas for the employee array*/
const employees = [
  {
    id: "748",
    firstName: "Freddy",
    lastName: "Krueguer",
    startDate: "10/31/78",
    department: "Human Ressources",
    dateOfBirth: "02/23/60",
    street: "Elm Street",
    city: "Springwood",
    state: "OH",
    zipCode: "45011",
  },
  {
    id: "1384",
    firstName: "Jason",
    lastName: "Voorhees",
    startDate: "10/31/81",
    department: "Marketing",
    dateOfBirth: "11/02/61",
    street: "Franklin Street",
    city: "Crystal Lake",
    state: "NJ",
    zipCode: "75624",
  },
  {
    id: "258",
    firstName: "Ash",
    lastName: "Williams",
    startDate: "04/11/89",
    department: "Sales",
    dateOfBirth: "06/02/69",
    street: "Clatu Verata Street",
    city: "Elk Grove",
    state: "MI",
    zipCode: "96425",
  },
  {
    id: "75",
    firstName: "Annie",
    lastName: "Wilkes",
    startDate: "10/01/89",
    department: "Legal",
    dateOfBirth: "09/05/70",
    street: "Sheldon Street",
    city: "Sidewinter",
    state: "CO",
    zipCode: "24586",
  },
  {
    id: "748",
    firstName: "Freddy",
    lastName: "Krueguer",
    startDate: "10/31/78",
    department: "Human Ressources",
    dateOfBirth: "02/23/60",
    street: "Elm Street",
    city: "Springwood",
    state: "OH",
    zipCode: "45011",
  },
  {
    id: "1384",
    firstName: "Jason",
    lastName: "Voorhees",
    startDate: "10/31/81",
    department: "Marketing",
    dateOfBirth: "11/02/61",
    street: "Franklin Street",
    city: "Crystal Lake",
    state: "NJ",
    zipCode: "75624",
  },
  {
    id: "258",
    firstName: "Ash",
    lastName: "Williams",
    startDate: "04/11/89",
    department: "Sales",
    dateOfBirth: "06/02/69",
    street: "Clatu Verata Street",
    city: "Elk Grove",
    state: "MI",
    zipCode: "96425",
  },
  {
    id: "75",
    firstName: "Annie",
    lastName: "Wilkes",
    startDate: "10/01/89",
    department: "Legal",
    dateOfBirth: "09/05/70",
    street: "Sheldon Street",
    city: "Sidewinter",
    state: "CO",
    zipCode: "24586",
  },
  {
    id: "748",
    firstName: "Freddy",
    lastName: "Krueguer",
    startDate: "10/31/78",
    department: "Human Ressources",
    dateOfBirth: "02/23/60",
    street: "Elm Street",
    city: "Springwood",
    state: "OH",
    zipCode: "45011",
  },
  {
    id: "1384",
    firstName: "Jason",
    lastName: "Voorhees",
    startDate: "10/31/81",
    department: "Marketing",
    dateOfBirth: "11/02/61",
    street: "Franklin Street",
    city: "Crystal Lake",
    state: "NJ",
    zipCode: "75624",
  },
  {
    id: "258",
    firstName: "Ash",
    lastName: "Williams",
    startDate: "04/11/89",
    department: "Sales",
    dateOfBirth: "06/02/69",
    street: "Clatu Verata Street",
    city: "Elk Grove",
    state: "MI",
    zipCode: "96425",
  },
  {
    id: "75",
    firstName: "Annie",
    lastName: "Wilkes",
    startDate: "10/01/89",
    department: "Legal",
    dateOfBirth: "09/05/70",
    street: "Sheldon Street",
    city: "Sidewinter",
    state: "CO",
    zipCode: "24586",
  },
];

export default employees;
