/*Mocked datas for the employee array*/
const employees = [
  {
    id: "748",
    firstName: "Freddy",
    lastName: "Krueguer",
    startDate: "10/31/78",
    department: "Human Ressources",
    dateOfBirth: "02/23/60",
    street: "Elm Street",
    city: "Springwood",
    state: "OH",
    zipCode: "45011",
  },
  {
    id: "1384",
    firstName: "Jason",
    lastName: "Voorhees",
    startDate: "10/31/81",
    department: "Marketing",
    dateOfBirth: "11/02/61",
    street: "Franklin Street",
    city: "Crystal Lake",
    state: "NJ",
    zipCode: "75624",
  },
  {
    id: "258",
    firstName: "Ash",
    lastName: "Williams",
    startDate: "04/11/89",
    department: "Sales",
    dateOfBirth: "06/02/69",
    street: "Clatu Verata Street",
    city: "Elk Grove",
    state: "MI",
    zipCode: "96425",
  },
  {
    id: "75",
    firstName: "Annie",
    lastName: "Wilkes",
    startDate: "10/01/69",
    department: "Legal",
    dateOfBirth: "09/05/70",
    street: "Sheldon Street",
    city: "Sidewinter",
    state: "CO",
    zipCode: "24586",
  },
  {
    id: "7452",
    firstName: "Sam",
    lastName: "Raimi",
    startDate: "02/14/63",
    department: "Human Ressources",
    dateOfBirth: "01/05/60",
    street: "Ted Boulevard",
    city: "Hackett's Quarry",
    state: "TX",
    zipCode: "32684",
  },
  {
    id: "257",
    firstName: "Stanley",
    lastName: "Kubrick",
    startDate: "07/16/67",
    department: "Marketing",
    dateOfBirth: "11/04/62",
    street: "Moon Street",
    city: "Earth Circle",
    state: "CA",
    zipCode: "24685",
  },
  {
    id: "862",
    firstName: "Bruce",
    lastName: "Campbell",
    startDate: "25/12/86",
    department: "Sales",
    dateOfBirth: "08/09/68",
    street: "Groovy Street",
    city: "Las Vegas",
    state: "UH",
    zipCode: "53694",
  },
  {
    id: "128",
    firstName: "Brigitte",
    lastName: "Lecordier",
    startDate: "03/05/81",
    department: "Legal",
    dateOfBirth: "18/07/70",
    street: "Dragon House",
    city: "Tokyo",
    state: "JP",
    zipCode: "12759",
  }
];

export default employees;
